# -*- coding: utf-8 -*-
"""ba1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AdExc4Ds4_gNMF4gfhHv0FufC_Ca28ss

Counting words
"""

def PatternCount(pattern,text):
  count=0
  for i in range(0,len(text)-len(pattern)+1):
    if(text[i:i+len(pattern)]==pattern):
      count=count+1
  return count

pattern=''
text=''

PatternCount(pattern,text)