# -*- coding: utf-8 -*-
"""ba1f.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14QQ7BWwxbwfFdHfDvaX9JOmvUqmcL0Ft
"""

def MinSkew (Genome):

# ide se po redu po Genomu i ako se na određenom mjestu nalazi C oduzimamo
# 1, a ako se nalazi G dodajemo 1 i rezultat za taj index spremamo u dictionary
# index je kljuc, a rezultat vrijednost u tom kljucu
# uzmemo one pozicije (kljuceve) gdje je razlika najmanja

    br = 0
    dictionary = {0:0} #pocinjemo s 0
    ispis = ""
    
    for i in range (0, len(Genome)):
        if (Genome[i] == "C"):
            br -= 1
        elif (Genome[i] == "G"):
            br += 1
        dictionary[i+1] = br 

    minValue = min(dictionary.values())

    for key in dictionary.keys():
        if dictionary[key] == minValue:
            ispis += str(key) + " "

    return ispis

f=open('rosalind_ba1f.txt')
lista=f.readlines()

print(MinSkew(lista[0]))