# -*- coding: utf-8 -*-
"""ba1g.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MmajczYbkYAObxR-PdTD_jgyyULkQZ1w

Hamming Distance Problem:

Compute the Hamming distance between two strings.

Input: Two strings of equal length.

Output: The Hamming distance between these strings.
"""

def HammingDistance(p,q):
  if(len(p)!=len(q)):
    return -1 
  dist=0
  for i in range(0,len(p)):
    if(p[i]!=q[i]):
      dist=dist+1
  return dist

p='GGGCCGTTGGT'
q='GGACCGTTGAC'

HammingDistance(p,q)