# -*- coding: utf-8 -*-
"""ba1k.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1llJLU0w8J423AyUghEzizj4Lh52Xs53g

Given an integer k, we define the frequency array of a string Text as an array of length 4k, where the i-th element of the array holds the number of times that the i-th k-mer (in the lexicographic order) appears in Text 

Computing a Frequency Array
Generate the frequency array of a DNA string.

Given: A DNA string Text and an integer k.

Return: The frequency array of k-mers in Text.
"""

def FillArray(List,t): 
    i = 0 
    counter = 0 
    
    while (i != len(List)):
            
        if (counter < pow(4,t)):
            List[i] += "A"
        elif ((counter >= pow(4,t)) & (counter < 2*pow(4,t))):
            List[i] += "C"
        elif ((counter >= 2*pow(4,t)) & (counter < 3*pow(4,t))):
            List[i] += "G"
        elif ((counter >= 3*pow(4,t)) & (counter < 4*pow(4,t))):
            List[i] += "T"

        counter += 1
        if counter >= 4*pow(4,t): 
            counter = 0

        i += 1

    return List

def FrequencyArray(Text,k):

    kmers = [""]*pow(4,k)
    frequency =[0]*pow(4,k)
    ispis = ""

    for i in range (k-1,-1,-1):
        kmers = FillArray(kmers,i) 
    
    for i in range (0,len(Text) - k + 1):
        frequency[kmers.index(Text[i:i+k])] += 1
    
    for element in frequency:
        ispis += str(element) + " "
        
    return ispis

FrequencyArray('GGGAGCATTAAGAAGCAGATGAGCGAATCTCTCGCAGCGACGATCTCGGTTGATTGTGTCCATTATTTGGTTGTATACAGAAGATCGAGAAGTGCTAAACTTTCTATGGGCGGTGCGCGCAGTCTGAGATGCGACCTGACCTATTCAGGACGCACGCGGATAGGCATTCTTAATGCGAATTAGCATCTGGTCCTTTATGGAATCAAGATAGTCAAACGATGACCCTCTAGTTAATCGCTACAATGAAAGACTCTCTCGACTCGTGAGGCGCGGAGTTTACCGCCAATCCAAGTGCGCCACAGAATAGGATTCAGCGGGTTGTCTCCCCCCGTGTCGATGGAATCTGAGGATTGCCTCTGAGGGACTCTTGGCTTCGATGCGGAGTGCCAGAGTGCAGGGCATCATTGGGTACAATAGGCTCTATACTCGATGAACCTAAACCCTTTGAATTTGCATGCAGTACAACTCCGAACGGCGTGACACGATGTGACAAGTATGTGCTTCTCGGATGGGTTAAACACTTTATTACCTATACCGCCAGATCACTGAGCCATCTCCTTGATCAAGCGAGGTCTATGTGTACGCATTCGCCGGCCAGTCTCGGTATTCTGGAAAGACATCCCCAAGCGCTGAGGT',7)