# -*- coding: utf-8 -*-
"""ba2f.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oh5Z_-VptjQRFLrGImq4e5ErLei_tPRF

**Implement RandomizedMotifSearch**

Given: Positive integers k and t, followed by a collection of strings Dna.

Return: A collection BestMotifs resulting from running RandomizedMotifSearch(Dna, k, t) 1000 times. Remember to use pseudocounts!
"""

def Row(char):

    if char == 'A':
        return 0
    if char == 'C':
        return 1
    if char == 'G':
        return 2
    if char == 'T':
        return 3


def Probability(kmer, Profile):

    prob = 1
    for i in range(0,len(kmer)):

        char = kmer[i]
        row = Row(char)
        prob *= Profile[row][i]

    return prob

def ProfileMostProbable_kMer(Text, k, Profile):

    maximum = Probability(Text[0:k],Profile)
    most_probable = Text[0:k]
    
    for i in range(1,len(Text) - k + 1):

        if (Probability(Text[i:i+k],Profile) > maximum):

            maximum = Probability(Text[i:i+k],Profile)
            most_probable = Text[i:i+k]

    return most_probable

def GetMotifs(Profile, Dna):

    Motifs = []
    k = len(Profile[0])
    
    for i in range(0,len(Dna)):

        Motifs.append(ProfileMostProbable_kMer(Dna[i], k, Profile))

    return Motifs

def MaxNmbrOfOccurencesOfLetterInColumn(Motifs,j):

    countACGT = [0,0,0,0]
    for i in range(0,len(Motifs)):

        if(Motifs[i][j] == 'A'):
            countACGT[0] +=1
        elif(Motifs[i][j] == 'C'):
            countACGT[1] +=1
        elif(Motifs[i][j] == 'G'):
            countACGT[2] +=1
        elif(Motifs[i][j] == 'T'):
            countACGT[3] +=1

    return max(countACGT)

def Score(Motifs):

    score = 0;
    for i in range(0,len(Motifs[0])):

        score += (len(Motifs) - MaxNmbrOfOccurencesOfLetterInColumn(Motifs,i))

    return score

def FormProfileWithPseudocounts(strings):

    n = len(strings)
    k = len(strings[0])

    Profile = []

    for m in range (0,4):
        
        ProfileRow = [1]*k
        for i in range(0,k):
            for j in range(0,n):
                row = Row(strings[j][i])
                if m == row:
                    ProfileRow[i] += 1
                    
            ProfileRow[i] = ProfileRow[i]/(n + 4)
                    
        Profile.append(ProfileRow)

    return Profile

from random import randint

def Random(N):

    return randint(0,N)

def RandomizedMotifSearch(k,t,Dna):

    n = len(Dna[0])
    Motifs = []
    BestMotifs = []
    
    for i in range(0,t):

        '''
        biram random pocetnu poziciju k-mera u svakom stringu iz Dna
        '''
        position = Random(n-k)
        Motifs.append(Dna[i][position: position+k])

    BestMotifs = Motifs

    while(True):

        Profile = FormProfileWithPseudocounts(Motifs)
        Motifs = GetMotifs(Profile,Dna)

        if Score(Motifs) < Score(BestMotifs):
            BestMotifs = Motifs

        else:
            break

    return BestMotifs

def Output(array):

    print ('\n'.join(array))

f=open('rosalind_ba2f.txt')
lines=f.readlines()

k = int(lines[0].strip('\n').split(' ')[0])
t = int(lines[0].strip('\n').split(' ')[1])
Dna = []

for i in range(1,len(lines)):
    Dna.append(lines[i].strip('\n'))

'''
Moram 1000 puta izvrsiti algoritam i izabrati rezultat s najboljim score-om
'''
BestMotifs = RandomizedMotifSearch(k,t,Dna)

for i in range(1,1000):

    Motifs = RandomizedMotifSearch(k,t,Dna)
    if Score(Motifs) < Score(BestMotifs):
        BestMotifs = Motifs

Output(BestMotifs)