# -*- coding: utf-8 -*-
"""ba3a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t_Ff6anTc-EJ09TeDfaNHQmPiluPCtty

**String Composition Problem**

Generate the k-mer composition of a string.

Given: An integer k and a string Text.

Return: Compositionk(Text) (the k-mers can be provided in any order).
"""

def Composition(k, Text):

    composition = ""
    
    for i in range (0, len(Text) - k + 1):
        # ispis k-mera jedan ispod drugog
        composition += Text[i:i+k] + "\n"

    return composition

text=""

print(Composition(3,text))