# -*- coding: utf-8 -*-
"""ba4a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19X_e2k3bP8I0UT9OUiataUyqn8CP_8bx
"""

def SymbolToNumber(symbol):
    if symbol == "A":
        return 0
    elif symbol == "C":
        return 1
    elif symbol == "G":
        return 2
    elif symbol == "U":
        return 3

def PatternToNumber(Pattern):
    if Pattern == "":
        return 0
    symbol = Pattern[len(Pattern)-1]
    prefix = Pattern[0:len(Pattern)-1]
    return 4*PatternToNumber(prefix) + SymbolToNumber(symbol)

def RNAtoAminoAcid(Pattern):
    Amino = 'KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSS*CWCLFLF' # amino kiseline
    out = ""
    for i in range (0, len(Pattern) - 3 + 1, 3):
        # svakom 3-meru je pridruzena po jedna amino kiselina
        amino_index = PatternToNumber(Pattern[i:i+3])
        amino_acid = Amino[amino_index]
        if amino_acid != '*':
            out += amino_acid
    return out

f=open('rosalind_ba4a.txt')
lista=f.readline()

print(RNAtoAminoAcid(lista).strip('\n'))