# -*- coding: utf-8 -*-
"""ba4d.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tusysUx89qfkY4ea0Mis7YDEFLFYG2kC

**Counting Peptides with Given Mass Problem**

Compute the number of peptides of given total mass.

Given: An integer m.

Return: The number of linear peptides having integer mass m.
"""

def CountingPeptidesWithGivenMass(mass):
    
    AminoAcidMasses = set([57,71,87,97,99,101,103,113,113,114,115,128,128,129,131,137,147,
            156,163,186])

    counter = dict()

    return CountingAllCombinations(mass,counter,AminoAcidMasses)

def CountingAllCombinations(mass,counter,aa_masses):

    if mass == 0:
        return 1

    if mass < 0:
        return 0

    if mass in counter:
        return counter[mass]


    counter[mass] = 0
    for element in aa_masses:

        counter[mass] += CountingAllCombinations(mass - element,counter,aa_masses)


    return counter[mass]

f=open('rosalind_ba4d.txt')
line=f.readline()

print(CountingPeptidesWithGivenMass(int(line.strip('\n'))))