# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zYGHZ7wuKOcfTsI2rJnFUdZOmv6_o6wV

#pokusaj uploadanja
"""